name: Nebula Build
permissions:
  contents: read
  actions: write
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  buildmultijdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of some major Java version(s), as well as specific LTS version(s)
        java: [17, 21, 25]
    name: Gradle Build without Publish
    steps:
      - uses: actions/checkout@v4
      - name: Setup git user
        run: |
          git config --global user.name "Nebula Plugin Maintainers"
          git config --global user.email "nebula-plugins-oss@netflix.com"
      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: |
            17
            21
            ${{ matrix.java }}
          java-package: jdk
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-overwrite-existing: true
      - name: Gradle build
        run: ./gradlew --stacktrace build
        env:
          JDK_VERSION_FOR_TESTS: ${{ matrix.java }}
